//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skewworks.Tinkr
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Skewworks.Tinkr.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            g3 = -28150,
            g4 = -27209,
            upleft = -19585,
            down = -19471,
            gray = -10599,
            g2 = -8186,
            left = -6141,
            right = -3458,
            downleft = -1091,
            upright = 13,
            g1 = 10863,
            green = 11363,
            red = 15083,
            active_cir = 15463,
            inactive_cir = 18133,
            up = 19228,
            blue = 19784,
            downright = 24437,
        }
    }
}
