//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skewworks.NETMF.Resources
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Skewworks.NETMF.Resources.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            droid11italic = -29309,
            droid8bold = -26679,
            droid9 = -25077,
            droid9italic = -17892,
            droid8 = -14331,
            droid9bolditalic = -12322,
            droid12bold = -6103,
            droid11 = 1576,
            droid16 = 1577,
            droid12 = 1581,
            droid16bolditalic = 3382,
            droid16bold = 6189,
            droid11bold = 8164,
            droid12bolditalic = 9594,
            droid9bold = 17845,
            droid12italic = 18411,
            droid8italic = 19149,
            droid16italic = 26729,
            droid11bolditalic = 29421,
            droid8bolditalic = 29804,
        }
    }
}
