//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skewworks.NETMF.Controls
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Skewworks.NETMF.Controls.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            clear = -31384,
            down = -19471,
            shift1 = -8812,
            left = -6141,
            next = -5689,
            right = -3458,
            file = 4335,
            back = 6228,
            shift2 = 13480,
            folder = 14568,
            del = 15669,
            up = 19228,
            shift3 = 20075,
            _return = 20115,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            chk16 = -18174,
            chk12 = -18162,
            chk72 = -10475,
            chk48 = -727,
            chk32 = 1379,
            chk8 = 9661,
            chk24 = 29498,
        }
    }
}
